# server
server:
  port: ${PORT:8080}

spring:

  application:
    name: trackfolio

  # Database
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

    hikari:
      # --- Your existing setup ---
      connection-timeout: 50000          # Wait up to 50s for a connection before failing
      initialization-fail-timeout: -1    # Don't fail immediately if DB is unavailable
      maximum-pool-size: 10
      idle-timeout: 600000               # 10 min
      max-lifetime: 1500000              # 25 min (< DB idle kill), avoids stale reuse

      # --- Additions for cold start handling ---
      minimum-idle: 0                    # Don’t keep idle stale conns after suspend
      validation-timeout: 5000           # Validate conns within 5s
      connection-test-query: SELECT 1    # Always check before handing out a conn
      auto-commit: true                  # Ensure clean state per new connection


  # Hibernate
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    open-in-view: false

    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

# JWT Secret
jwt:
  secret: ${JWT_SECRET}

# Custom microservice for chatbot requests
aicore:
  url: ${aicore_url}

# allowed url for CORS
app:
  frontend-url: ${FRONTEND_URL}

# Health check
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true